### ISSUE TITLE
Should the terraform-basic-example create a state file?

### ISSUE THREAD

**Issue by blundell** [gruntwork-io/terratest#1060]
Really appreciate the basic examples, thank you, its helping me understand the building blocks (after diving in to AWS stuff then backtracking :-))

I wanted to understand, should this example https://github.com/gruntwork-io/terratest/tree/master/examples/terraform-basic-example create a `terraform.tfstate` [(ref)](https://www.terraform.io/language/state) file when it is ran? 
Or is it "too simple" to need to generate state?

( I ask because I am using your example in combination with [jetbrains-gradle-plugins](https://github.com/JetBrains/jetbrains-gradle-plugins/blob/master/docs/TERRAFORM.md) and I am not see'ing a `terraform.tfstate` file, so I am wondering if its the fact it's too basic a terraform setup, or the plugin is not generating it. )

TY!

**Comment by infraredgirl** [comment]
Hi Paul, the example should generate the Terraform state file when run with `terraform apply`. You can test that easily by running `terraform init` and `terraform apply` from the `terraform-basic-example` folder.

Looking at the documentation for the Jetbrains Gradle plugin that you linked (https://github.com/JetBrains/jetbrains-gradle-plugins/blob/master/docs/TERRAFORM.md#local-state-file) it looks like that plugin is indeed doing some local copying of the state file, so that might be the reason you are not seeing it as expected.

Hope that helps!
