### ISSUE TITLE
Azure tests return [no test files]

### ISSUE THREAD

**Issue by rdvansloten** [gruntwork-io/terratest#1119]
I've been trying to run tests for Azure resources, but I can't seem to get Azure specifically running. I've ran the example from the Quick Start successfully, but the Azure resources just won't. 

- macOS Monterey Version 12.3.1 (M1 Pro CPU)
- go version go1.18.1 darwin/arm64

Initially, using the Quick Start commands throws this error:
```
go test -v -timeout 30m 
package mymodule: build constraints exclude all Go files in
```

Going through issues, I understand I have to run this instead, using `-tags`:
```
go test -v -tags azure -timeout 30m
?       mymodule  [no test files]
```

My directory tree looks like this:
```
+ examples/mymodule
| - main.tf
+ test
| - mymodule.go
```

mymodule.go:
```
//go:build azure
// +build azure

// NOTE: We use build tags to differentiate azure testing because we currently do not have azure access setup for
// CircleCI.

package test

import (
	"testing"

	"github.com/gruntwork-io/terratest/modules/azure"
	"github.com/gruntwork-io/terratest/modules/terraform"
	"github.com/stretchr/testify/assert"
)

func TestTerraformAzureLoadBalancerExample(t *testing.T) {
	t.Parallel()

	// subscriptionID is overridden by the environment variable "ARM_SUBSCRIPTION_ID"

	// Configure Terraform setting up a path to Terraform code.
	terraformOptions := &terraform.Options{
		// The path to where our Terraform code is located
		TerraformDir: "../examples/mymodule",

		// Variables to pass to our Terraform code using -var options
		Vars: map[string]interface{}{},
	}

	// At the end of the test, run `terraform destroy` to clean up any resources that were created.
	defer terraform.Destroy(t, terraformOptions)

	// Run `terraform init` and `terraform apply`. Fail the test if there are any errors.
	terraform.InitAndApply(t, terraformOptions)

	// Run `terraform output` to get the values of output variables
	resourceGroupName := terraform.Output(t, terraformOptions, "resource_group_name")
	lbName := terraform.Output(t, terraformOptions, "lb_name")

	t.Run("LoadBalancer", func(t *testing.T) {
		// Check if Load Balancer exists.
		actualLbExists := azure.LoadBalancerExists(t, lbName, resourceGroupName, subscriptionId)
		assert.True(t, actualLbExists)
	})
}
```

I have verified the folder exists. Even if I change the folder to nonsense, the same error pops up. This is a modified version of the Azure load balancer example in the repo. It doesn't seem to get to the stage of testing the files at all.

**Comment by yorinasub17** [comment]
1. Try removing the build tags in `mymodule.go`. We have that in our pipeline/examples so that we can run the azure tests in a different pipeline with different environment secrets, but you won't need that for your build.
2. In go testing (which terratest uses under the hood) all the test files have to end with the suffix `_test.go`, so you need to rename your `mymodule.go` file to `mymodule_test.go`.
3. Make sure you are running in the `test` folder.
4. In your `test` folder, run `go mod init github.com/MY_ORG/MY_REPO/test && go mod tidy` to ensure all the dependencies get defined and pulled down in `go.mod` and `go.sum` files.

After you've done all that, you should be able to run `go test -v -timeout 90m .` in the `test` folder to get the test to run.

**Comment by rdvansloten** [comment]
Hi @yorinasub17, renaming the file with _test helped! Thanks so much!
