### ISSUE TITLE
Add support for snapshot testing

### ISSUE THREAD

**Issue by jguionnet** [gruntwork-io/terratest#1377]
**Describe the solution you'd like**
[helm-unittest](https://github.com/helm-unittest/helm-unittest) as a great feature called [snapshot testing](https://github.com/helm-unittest/helm-unittest#snapshot-testing).

Sometimes you may just want to check that the rendered manifest did not change between helm package version without every details asserted.

**Describe alternatives you've considered**
None and neither did the community, see https://github.com/orgs/gruntwork-io/discussions/780

**Additional context**

**Comment by Mo0rBy** [comment]
Hello, I just came across this issue simply because it was fresh and at the top of the page.
For context, please read [this article](https://medium.com/@zelldon91/advanced-test-practices-for-helm-charts-587caeeb4cb). I believe this is how Camunda test their own Helm charts. It describes "Golden template files" and I think these are essentially snapshots.

Could be what you are looking for, or could be used for inspiration to add snapshots to this already great tool.
