### ISSUE TITLE
Migration to aws-sdk-go-v2?

### ISSUE THREAD

**Issue by artem-nefedov** [gruntwork-io/terratest#1432]
AWS SDK for Go (v1) is already in maintenance mode since July 31, 2024, and is moving towards end of life:
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/

Are there any plans to migrate Terratest to aws-sdk-go-v2?

**Comment by wakeful** [comment]
hey @artem-nefedov


Can you help test my PR #1451?
You can point to my **fork** by using the **replace** directive in your `go.mod` file.


```shell
go mod init github.com/wakeful/new-project
go mod edit -replace github.com/gruntwork-io/terratest@v0.47.2=github.com/wakeful/terratest@v0.48.0
go get github.com/gruntwork-io/terratest/modules/aws@v0.47.2
```

**Comment by artem-nefedov** [comment]
Seems done to me

**Comment by uchanchlani** [comment]
The changes introduced in PR #1451 modify the signatures of exposed functions, which is a breaking change. As a result, this should have triggered a major version bump from `0.47.2` to `1.0.0`, rather than a minor version bump to `0.48.0`.

For example, the function `NewEcsClientE` in `modules/aws/ecs.go` previously returned `*(aws/aws-sdk-go/service/)ecs.ECS`. After this PR, it now returns `*(aws-sdk-go-v2/service/)ecs.Client`. This breaking change impacts compatibility and aligns with semantic versioning principles, which mandate a major version increment for such updates.

**Comment by ZachGoldberg** [comment]
Hi @uchanchlani !  Thanks for the thoughtful feedback!  

Terratest is still pre-1.0, and as such does not have backwards compatibility guarantees within its major version of 0.  We tend to use minor version bumps to indicate when things might break.  Gruntwork is, however, pushing to get all of the [tools](https://blog.gruntwork.io/the-road-to-terragrunt-1-0-4d5a0b416086) it maintains to 1.0 and begin enforcing such a backwards compatibility promise, although we are not there yet.  I/we apologize if this causes any inconvenience along the way, however we feel its important that we have a stable foundation that we can commit to for a long time before officially releasing 1.0.
