### ISSUE TITLE
Terratest_log_parser ERROR

### ISSUE THREAD

**Issue by MichaelSmyth0184** [gruntwork-io/terratest#196]
Hi,

I seem to be getting a terrates_log_parser command not found error!

I tried the following commands, but the parser does not seem to get picked up.

`go test -v -run TestFunction | output.log 
`  
which produces a txt file of the test.

Then when I run

`terratest_log_parser -testlog test_ouptut.log -outputdir test_output
`
I get Terratest_log_parser command not found! Any help would be great.

**Comment by yorinasub17** [comment]
That seems to indicate that your shell couldn't resolve `terratest_log_parser` to the right binary. Some things to try:

- What does `which terratest_log_parser` output? Does it resolve to a file or does it error?
- How did you install it? Do you know exactly where the file is? What happens if you try running that exact file?

**Comment by MichaelSmyth0184** [comment]
Just gives a "Command not found" for terratest_log_parser. Does not resolve to a file either, same error.
How does one install terrates_log_parser? The fact I can run terratests successfully on my terraform should mean I have all the neccessary files no? I assumed dep init and ensure successfully pulled all packages from git-hub.
Thanks

**Comment by MichaelSmyth0184** [comment]
![image](https://user-images.githubusercontent.com/34038292/48434173-ee969700-e770-11e8-961a-e84fe5370acb.png)
Found the folder for log parser too on my machine.

**Comment by yorinasub17** [comment]
Ah sorry for the confusion from the documentation! So terratest ships two components:

- `terratest` the library, which you link to as part of the go tests (this is managed by `dep`)
- `terratest_log_parser` the binary, which is NOT managed by `dep` and something you have to explicitly install to use. The compiled versions are available for download from the [releases page](https://github.com/gruntwork-io/terratest/releases). You can download the one compatible for your platform and call it.

Note that if you depend on `terratest` using `dep`, it pulls in all the source code from the repository. But it does not actually link and compile everything unless you explicitly reference it in your source code. So while the binary source files exist, you can't actually call into it because it needs to be separately compiled into an executable binary.

**Comment by MichaelSmyth0184** [comment]
Ahhh okies yeah i didn't get that from the documentation lol.
Thanks, and by calling it in source code do you mean just reference the location of it?
Sorry I am a nooby at this.

Thanks

**Comment by yorinasub17** [comment]
> Ahhh okies yeah i didn't get that from the documentation lol.

Yup I am in the process of updating the documentation.

> Thanks, and by calling it in source code do you mean just reference the location of it?

Sorry that was just an explanation of why you have the source code but the binaries don't exist. The actual way to use it is through the binary. Here is the preview of the updated install section which might be helpful:

### Installing the utility binaries

Terratest also ships utility binaries that you can use to improve the debugging experience (see [Debugging interleaved
test output](#debugging-interleaved-test-output). The compiled binaries are shipped separately from the library in the [Releases page](https://github.com/gruntwork-io/terratest/releases).

To install a binary, download the version that matches your platform and place it somewhere on your `PATH`. For example
to install version 0.13.13 of `terratest_log_parser`:

```bash
# This example assumes a linux 64bit machine
# Use curl to download the binary
curl -o terratest_log_parser https://github.com/gruntwork-io/terratest/releases/download/v0.13.13/terratest_log_parser_linux_amd64
# Make the downloaded binary executable
chmod +x terratest_log_parser
# Finally, we place the downloaded binary to a place in the PATH
sudo mv terratest_log_parser /usr/local/bin
```

**Comment by MichaelSmyth0184** [comment]
Thank you yourinasub17, got it working!

Many thanks,

Michael
