### ISSUE TITLE
(Question) CircleCI Integration

### ISSUE THREAD

**Issue by MichaelSmyth0184** [gruntwork-io/terratest#265]
Hi,

I am wanting to know how to integrate TerraTest log outputs into a tool, much like the CircleCI one mentioned in the docs. Could you explain how the Config.yaml "_**https://github.com/gruntwork-io/terratest/blob/master/.circleci/config.yml**_" file provided is deployed? And what resources it requires to get it up and running.

Many thanks,

Michael

**Comment by yorinasub17** [comment]
Hi @MichaelSmyth0184 ,

We have a few public Terraform modules that make use of CircleCI which you can use as a sample:

- https://github.com/gruntwork-io/terraform-aws-influx/blob/master/.circleci/config.yml
- https://github.com/hashicorp/terraform-aws-vault/blob/master/.circleci/config.yml

The main idea is:

- Setup a circleCI job that has go setup. Our CI scripts are restricted to gruntwork subscribers, but you can refer to [official circleci docs](https://circleci.com/docs/2.0/language-go/) for alternative methods.
- In the circleci job, make sure terraform (and any other tools like packer) are available.
- Install the log parser by fetching from [the release](https://github.com/gruntwork-io/terratest/releases). We use the [gruntwork-installer](https://github.com/gruntwork-io/gruntwork-installer) to do this, but you can also use curl + chmod.

Once that is all setup, you can then run the tests using `go test`. What you want to make sure you do here is that:

- There is sufficient timeout (using `-timeout`), since infra tests tend to be long and go defaults to timing out tests longer than 10 minutes.
- All the log output is piped to a file.

Then, you can point `terratest_log_parser` to the output file, store in a tmp directory, and then tell circleci to store the artifacts.
