### ISSUE TITLE
(Question) Hot to prevent remote state file updating in terrafrom.Destory()?

### ISSUE THREAD

**Issue by KhlaponinIO** [gruntwork-io/terratest#286]
Hello everyone. I have a separate module, which is uses a remote Backend (s3 bucket). So that, I'm using the next code snippet for testing:
```
terraformOptions := &terraform.Options{
                TerraformDir: "../",

                BackendConfig: map[string]interface{}{
                        "bucket": tfstateBucketName,
                        "key":    tfstateBucketKey,
                        "region": tfstateBucketRegion,
                },
                Upgrade: false,
}
defer terraform.Destroy(t, terraformOptions)
terraform.InitAndApply(t, terraformOptions)
```
According to the [documentation](https://godoc.org/github.com/gruntwork-io/terratest/modules/terraform#Options) the `Upgrade: false` flag provides possibility to ignore previously-downloaded objects and install the latest version allowed within configured constancts.

But when `terraform.Destroy()` running, it will rewrite remote state file in the s3 bucket. Is there a way to prevent such behavior?

NOTE: in our case, I have one state file for different modules, so I don't want it to be modified.

Thanks in advance.

**Comment by klebediev** [comment]
Let me try to answer your question.
`Options.Upgrade` is just about `terraform init -upgrade=(true|false)`
It's default value (if not set) is `false` (if something isn't initialized explicitly it gets nil/0/false etc )

How `-upgrade` clause works is described here:
[here](https://www.terraform.io/docs/commands/init.html#upgrade), [here](https://www.terraform.io/docs/commands/init.html#child-module-installation) and [here](https://www.terraform.io/docs/commands/init.html#plugin-installation)

https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/init.go#L19

Not sure I understand correctly, but looks like you'd like to reuse plugins downloaded. Is that correct?
In this case [this functionality](https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache) is helpful

**Comment by yorinasub17** [comment]
AFAIK, I don't think there is a way to prevent `terraform destroy` from updating the remote state, if you have a remote state backend configured. I would either suggest:

- Using a different state file path/bucket for testing.
- Refactoring your modules so that the module you are testing doesn't impose any state config, and have thin wrapper modules that impose the state config. Then, use local state for test purposes.

The key thing here is figuring out a way to configure the backend such that the state for testing is segregated from the state you use in prod, instead of trying to figure out a way to control when state is saved by terraform.

**Comment by KhlaponinIO** [comment]
Thank you, guys! I solved problem by hiding terraform backend.tf file during test (simply rename it)

Now I may get state as data, but it wouldn't be updated.

Thank you for your help and so detailed explanation

**Comment by yorinasub17** [comment]
Glad to hear you got it working! Going to close this issue now.
