### ISSUE TITLE
In README.md, having HTTP healthcheck may be confusing the use-case for the newcomers

### ISSUE THREAD

**Issue by funkydorian** [gruntwork-io/terratest#295]

**Comment by funkydorian** [comment]
In README.md, having the HTTP check as the first example isn't a bit confusing? This endpoint is probably also the healthcheck endpoint of the AWS/Kubernetes. So practically this example may not be a real world use case, right?

**Comment by yorinasub17** [comment]
Hi @funkydorian thanks for the feedback!

To explain the current structure a bit, the examples are organized to ease into terratest fundamentals of setup, defer destroy, apply, and validate. The idea is that when you compare the basic with the http examples, it should hopefully show that the main structure is preserved and the only difference is the validation step. So while the specific http check may not be a real world use case (which I disagree with: sometimes you will want to check the http endpoint independent of the health checks, since those are two different configurations), the use of terratest to setup, defer destroy, apply, and validate is a real world use case.

**Comment by brikis98** [comment]
We have new, simpler "Hello, World" examples on the Terratest website now: https://terratest.gruntwork.io/
