### ISSUE TITLE
Add ansible test module

### ISSUE THREAD

**Issue by mauromedda** [gruntwork-io/terratest#305]
Hi everyone,

feature. I would like to have the Ansible test module in order to execute the following tests on roles and playbook.

- syntax
- lint
- run/converge
- idempotent

Mauro

**Comment by yorinasub17** [comment]
This does make sense, although I wonder if it fits into this repo (after all, this is called `terratest`)? I know we recently added similar support for helm, but in hindsight, that may not have been the best idea because we now have lots of issues related to dependency management arising from the fact that `helm` and `kubernetes/client-go` doesn't support `dep`.

At the moment, I am ok with adding in an ansible module but we might want to consider splitting up the repo to reduce the build footprint.

**Comment by mauromedda** [comment]
Probably, as you was saying in the comment above is better create a new repo for ansibletest
