### ISSUE TITLE
Testing Terraform modules in a different repo

### ISSUE THREAD

**Issue by MichaelSmyth0184** [gruntwork-io/terratest#313]
Hi,
I am wanting to know if it is possible to run TerraTest files from one repo testing Terraform Modules in another? The way I have my terraform laid out is that the Terraform modules are in seperate Git repos seperated from the TerraTest Repo. Simply passing the Path to TerraformDir "../Path_to_Module" will not work in my case, so I am wondering if there is a possible solution such as Terraform source to pull read from repo. 

`module "alb_ec2" {
    source = "git::https://sqsglobal.visualstudio.com/Terraform/_git/alb_ec2"
}`

Many thanks,

Michael

**Comment by yorinasub17** [comment]
Off the top of my head, there are a few ways to go about this:

- You can add terraform code in the test repo that calls out to the modules in the other repo as you suggested.
- You can clone the repos locally into a folder structure such that you can reference the modules on the local file system.
- You can clone the repo at runtime during the test into a subfolder using https://github.com/src-d/go-git, before calling out to terratest.

Each of these have their pros and cons. Note that we don't do any of these approaches so you should pick one that best fits your needs and run with it.

We like to keep our test code with the modules (easier to do continuous integration testing, reduced complexity overhead, test code can be updated and released with the module changes, more likely to fix tests because they are in the same place, block PRs based if there are test failures, etc), so all of our modules include the test files in the same repo. Naturally, terratest is optimized for that workflow, since that is the core workflow we take on a day to day basis.

**Comment by antoniaklja** [comment]
I came across the same issue. We'd like to source Terraform modules from external GitHub Enterprise repositories which are external dependencies in our integration tests. 

IMHO would be nice to implement support for optional `TerraformURL`, currently, there is `TerraformDir` only.

Terraform Modules Sourcing: https://www.terraform.io/docs/modules/sources.html#github

**Comment by yorinasub17** [comment]
> IMHO would be nice to implement support for optional `TerraformURL` parameter, currently, there is `TerraformDir` only

Implementing this would actually duplicate a lot of logic with Terragrunt, and it isn't a trivial amount of code. However, this made me realize that you could potentially do what you want using terragrunt. The minimal version of this would be where you define a `terragrunt.hcl` file that only points at the remote terraform module:

```
terraform {
  source = "bitbucket.org/hashicorp/terraform-consul-aws"
}
```

and then point `TerraformBinary` to `terragrunt`, and the `TerraformDir` to where the `terragrunt.hcl` file lives. Of course better to have `TerraformUrl`, but this solution is probably better from a long term maintainability perspective.
