### ISSUE TITLE
EC2 Security Group Operations

### ISSUE THREAD

**Issue by floresj** [gruntwork-io/terratest#315]
Hello! 

Would it be helpful to have some additional functions in the `aws` package for the following:

- Creating/Deleting EC2 security groups
- AttachingRevoking Ingress rules
- AttachingRevoking Egress rules

If so, here are some initial thoughts on possible `funcs`:

```go
func CreateSecurityGroupE(t *testing.T, groupName, description, vpcID string) (groupID string, err error) {}
func DeleteSecurityGroupE(t *testing.T, groupName) error{}
```

Then for applying `ingress/egress` rules

```go
func AttachSecurityGroupIngressRulesE(t *testing.T, groupName string, perms []*ec2.IpPermission) error {}
func AttachSecurityGroupEgressRulesE(t *testing.T, groupName string, perms []*ec2.IpPermission) error {}

// Corresponding revoke rules
func RevokeSecurityGroupIngressRulesE(t *testing.T, groupName string, perms []*ec2.IpPermission) error {}
```

I also thought maybe having an alternative method of adding `ingress`/`egress` rules like this:

```go
func AttachSecurityGroupIngressRuleE(t *testing.T, groupName string, fromPort, toPort int64, protocol string, ipRanges []*ec2.IpRange) error {}
func AttachSecurityGroupEgressRuleE(t *testing.T, groupName string, fromPort, toPort int64, protocol string, ipRanges []*ec2.IpRange) error {}
```

I figured I'd first suggest sticking with the native aws golang structs for `ec2.IpPermission`, `ec2.IpRange` for user inputs. Or is it preferable to have some wrapper structs in the `terratest/modules/aws` to facilitate this type of functionality? 

*Note I've only included the `<funcName>E` error funcs in the example for brevity.*

**Comment by yorinasub17** [comment]
Can you share your use case for these functions? While these functions seem reasonable, they appear to be modification APIs. In general, the terratest philosophy is to deploy resources using terraform and then verifying that what you deployed is correct. The modules are meant to provide helper functions used for verification purposes, and modifying/creating resources should be optimized for those contexts.

So I want to understand your needs for modifying the security groups, and hearing a concrete test case scenario that you have which these functions would help would be a good way to understand that.

**Comment by floresj** [comment]
Thanks for the feedback! My main use case was to have a way to create temporary SSH Keys (which you all have funcs for) and temporary security groups when we provision new instances much like how `packer` behaves. Then at the end of the test run, I can blow them away. However, I can see how this may not align with the intent of terratest.

**Comment by yorinasub17** [comment]
Hmm I am leaning towards avoiding these functions in that case as it is not as compelling of a use case. The use case of temporarily creating dependent resources to unit test modules is something that comes up, but we find that using go functions to do this makes the tests highly brittle and complex (have to add waiting, retry logic, failure handling, logging, etc) and difficult to cull later when tests fail (because of forgotten logging, or not being able to rerun to delete the resources). Additionally, this is a slippery slope that could down the line make terratest expose every resource as a function (should we add VPCs to the mix? what about IAM roles? or an RDS instance?).

We instead like to use wrapper Terraform modules around the modules we test, which provide all the temporary resources, and target our tests against those. Doing so allows us to take full advantage of terraform life cycles and resources without extending terratest too far. For an example of this style of module testing, take a look at our open source modules, like [terraform-aws-influx](https://github.com/gruntwork-io/terraform-aws-influx) and [terraform-google-static-assets](https://github.com/gruntwork-io/terraform-google-static-assets/). The core modules are in the `modules` folder, and the wrapper code is in the `examples` folder. We then write tests that call out to the `examples`, not the `modules`, with each example being a standalone terraform module that deploys everything necessary for each of the submodules, thereby implicitly testing the underlying modules.

In general we draw the line for these class of functions with Terraform compatibility: if something is hard to do in terraform, then we have create/modify functions in terratest. For example, SSH key generation is not something that is recommended to be done in terraform. This is because of state leak and security concerns. We created the SSH key functions so that we can create temporary keys that only last as long as the test lasts, storing the SSH keys in memory (or tmp storage) so that we can SSH into the EC2 instances launched with it and cull them at the end of the test. Another example is AMI creation, where Terraform doesn't have provider support.

Given that, are there some things in your module that make it hard to create these temporary security groups in terraform?

**Comment by floresj** [comment]
I appreciate the explanations and examples. I really like the idea of using the wrapper Terraform modules to provide temporary/setup resources. It totally makes sense. I can see how that keeps the go code simpler and easier to reason about while leveraging Terraform for what's it great at.. managing resources. Your comments about the SSH key functions really cleared things up for me because I was curious as to what type of capabilities made sense to be incorporated into terratest.

My last question is around the wrapper Terraform modules to test modules. One of the tools we're starting to incorporate is `inspec` for some of our OS configuration. I initially was executing `inspec` from the `go` side. However, I could see that being executed from a wrapper TF module as a `local-exec` provisioner. Would executing something like that be a candidate for running from TF over using say the `shell.Command` stuff? 

Thanks again!

**Comment by yorinasub17** [comment]
> Would executing something like that be a candidate for running from TF over using say the shell.Command stuff?

This depends on a few factors, but the two key questions to ask are when do you want the test to run, and how are you consuming the outputs? I am not very familiar with `inspec`, but a cursory look indicates it is a OS testing tool. I am assuming this has a lot of different ways it outputs its results, and requirements on which services should be up.

Terraform's `local-exec` provisioner is not very good at implementing things like waiting logic (since it is all bash, or you embed a interpreted language script like python) or for chaining actions based on the output. For example, if `inspec` outputs its results in `json` and you want to chain actions based on the interpolating results, you will most likely end up writing some code in an imperative language outside of terraform.

In general, my logic is that if you have to write a script anyway, then it doesn't make much sense to force it into terraform and instead run it through go in the terratest framework.

The exception to this rule is if it is something that should be baked into the module itself. For example, the terraform resource for ECS service deployments doesn't wait for rollouts to happen. In this scenario, a rollout might fail even though `terraform apply` succeeds. If you want to support a feature in your module that waits for the service to roll out, then this will most likely be implemented as a `local-exec` script inside the module.

So if you want to always run `inspec` whenever *any* instance is deployed using your module, then it makes sense to bake that into the module (via a `local-exec` provisioner), regardless of chaining the outputs, since it is a core feature of your terraform module.

**Comment by floresj** [comment]
Closing the issue because I received clarification and guidance on best approaches. Thanks again!

**Comment by floresj** [comment]
Hey @yorinasub17 I know this is closed but just wanted to let you know that the wrapper Terraform modules idea is working out perfectly for some of my use-cases. Thank you and the other gruntwork folks for always taking the time to provide very thoughtful and complete answers to our questions. As a consumer, it makes me want to continue to use these awesome tools. And as a contributor, I hope to put in some more PR's in the future. You all are rockin' it. 👍

**Comment by yorinasub17** [comment]
Glad to hear that worked well.

And thanks for the kind words! Looking forward to more of your PRs!
