### ISSUE TITLE
Tests are complicated... is it possible to re-write basic test to support new approach without $GOPATH?

### ISSUE THREAD

**Issue by mrPsycho** [gruntwork-io/terratest#316]
Hello,

i'm trying to understand all this stuff with GO, and have confuse:
* GOPATH is not necessary due to new approach: https://stackoverflow.com/questions/21001387/how-do-i-set-the-gopath-environment-variable-on-ubuntu-what-file-must-i-edit/53026674#53026674
and when i'm trying to run basic test (https://github.com/gruntwork-io/terratest/tree/master/examples/terraform-basic-example)  - i see error connected to GOPATH.

* are there any best practicies for pointing that GOPATH for this project terratest?  
This would be great to hear, cause i would like to introduce terratest to our team, but... i can't understand how to setup it correctly, so everyone will use it by somewhat template.

**Comment by mrPsycho** [comment]
```
mrpsy@LVAGPLTP2798:~/repos/terratest/test$ go test -v -run TestTerraformBasicExample
# _/home/mrpsy/repos/terratest/test
packer_basic_example_test.go:10:2: cannot find package "github.com/aws/aws-sdk-go/aws" in any of:
	/usr/lib/go-1.10/src/github.com/aws/aws-sdk-go/aws (from $GOROOT)
	/home/mrpsy/repos/terraform_conf/src/src/github.com/aws/aws-sdk-go/aws (from $GOPATH)
FAIL	_/home/mrpsy/repos/terratest/test [setup failed]
```

this what i see.

**Comment by mrPsycho** [comment]
ok, i figured it out. 

but:
```
mrpsy@LVAGPLTP2798:~/src/github.com/gruntwork-io/terratest$ dep ensure
dep: WARNING: Unknown field in manifest: prune
dep: WARNING: Unknown field in manifest: require
ensure Solve(): No versions of google.golang.org/api met constraints:
	master: unable to update checked out version: : command failed: [git checkout 19ff8768a5c0b8e46ea281065664787eefc24121]: exit status 1
	v0.5.0: Could not introduce google.golang.org/api@v0.5.0, as it is not allowed by constraint master from project github.com/gruntwork-io/terratest.
	v0.4.0: Could not introduce google.golang.org/api@v0.4.0, as it is not allowed by constraint master from project github.com/gruntwork-io/terratest.
	v0.3.2: Could not introduce google.golang.org/api@v0.3.2, as it is not allowed by constraint master from project github.com/gruntwork-io/terratest.
	v0.3.1+alpha: Could not introduce google.golang.org/api@v0.3.1+alpha, as it is not allowed by constraint master from project github.com/gruntwork-io/terratest.
	v0.3.1: Could not introduce google.golang.org/api@v0.3.1, as it is not allowed by constraint master from project github.com/gruntwork-io/terratest.
	v0.3.0: Could not introduce google.golang.org/api@v0.3.0, as it is not allowed by constraint master from project github.com/gruntwork-io/terratest.
	v0.2.0: Could not introduce google.golang.org/api@v0.2.0, as it is not allowed by constraint master from project github.com/gruntwork-io/terratest.
	v0.1.0: Could not introduce google.golang.org/api@v0.1.0, as it is not allowed by constraint master from project github.com/gruntwork-io/terratest.
	v0.3.1-alpha: Could not introduce google.golang.org/api@v0.3.1-alpha, as it is not allowed by constraint master from project github.com/gruntwork-io/terratest.
	master: unable to update checked out version: : command failed: [git checkout b50168921e183c95644f04416271d702a730550c]: exit status 1
	dartman: Could not introduce google.golang.org/api@dartman, as it is not allowed by constraint master from project github.com/gruntwork-io/terratest.
```

why?

**Comment by mrPsycho** [comment]
```mrpsy@LVAGPLTP2798:~$ go get -v github.com/gruntwork-io/terratest
github.com/gruntwork-io/terratest (download)
package github.com/gruntwork-io/terratest: no Go files in /home/yn/src/github.com/gruntwork-io/terratest
```

its something strange, that it is so complicated to install this :(

**Comment by yorinasub17** [comment]
Hi,

Apologies for the difficulties you are running into. I understand the pain and we are actively working on figuring out ways to improve this.

With that said, here are a few answers and pointers:

> GOPATH is not necessary due to new approach

Unfortunately, our project has not been updated yet to use gomodules (which is a requirement for that approach). In fact, all of the issues you ran into beyond that are because the source repo isn't cloned in the GOPATH src path. You can see the discussion on [this PR](https://github.com/gruntwork-io/terratest/pull/264).

With that said, I would not recommend running the terratest examples directly from the terratest repo unless you are contributing to the project, as it is not a good starting point for your own modules. Here is what I would suggest trying:

- First create a new blank folder in the gopath. This can be in any folder structure as long as it is in the GOPATH, which based on the error messages you have it will be `/home/mrpsy/src/`.
- In the folder, create two folders: `example` and `test`.
- In the `example` folder, copy [the basic terraform example](https://github.com/gruntwork-io/terratest/tree/master/examples/terraform-basic-example).
- In the `test` folder, copy [the corresponding test](https://github.com/gruntwork-io/terratest/blob/master/test/terraform_basic_example_test.go).
- In the `test` folder, create a `Gopkg.toml` file with the following content:
```
[[constraint]]
  name = "github.com/gruntwork-io/terratest"
  version = "0.16.0"
```

Then, here are the steps to run the tests:

1. In the `test` folder, run `dep ensure`
1. Once that finishes, run `go test -v .`

**Comment by yorinasub17** [comment]
Once you have the above, that can be a good starting point / scaffold for all your terraform modules going forward. Note that the same thing can be done for the helm if you intend on using those (see https://github.com/gruntwork-io/terratest-helm-testing-example).

**Comment by mrPsycho** [comment]
cool, thanks) 


also found, that it is not working with go 1.12. 
but for my purpose it is ok.

**Comment by yorinasub17** [comment]
Can you share the error message you get with go 1.12? I want to create a new issue for it since we should be compatible.

**Comment by mrPsycho** [comment]
yes. 

forgot to copy&paste original one... but just upgraded GO and see this:
```
mrpsy@LVAGPLTP2798:~/go/src/test$ go test -v .
warning: GOPATH set to GOROOT (/home/mrpsy/go) has no effect
# test
package test (test)
	imports github.com/gruntwork-io/terratest/modules/terraform
	imports github.com/gruntwork-io/terratest/modules/shell
	imports bufio: cannot find package "bufio" in any of:
	/home/mrpsy/go/src/test/vendor/bufio (vendor tree)
	/home/mrpsy/go/src/bufio (from $GOROOT)
	($GOPATH not set. For more details see: 'go help gopath')
FAIL	test [setup failed]
```

same command on go.1.10 (which was installed by `apt install golang`) works.

**Comment by mrPsycho** [comment]
i'm sorry, it was my fault
it works with go 1.12.

**Comment by jawoponlenuigalwaycom** [comment]
![image](https://user-images.githubusercontent.com/56373264/75372780-f116f480-58c0-11ea-8b66-d181ebcda39c.png)
 Any ideas? whats the corrcet way to define project id as per this point?
![image](https://user-images.githubusercontent.com/56373264/75372908-2885a100-58c1-11ea-81df-97ae3897711a.png)

**Comment by yorinasub17** [comment]
Hi @jawoponlenuigalwaycom  can you file a new issue with this exact content, since it is unrelated to this topic which is closed? Thanks!

**Comment by jawoponlenuigalwaycom** [comment]
I'm kind of new to raising issues😅, thanks done

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
