### ISSUE TITLE
Check instance port is reachable

### ISSUE THREAD

**Issue by carlos4ndre** [gruntwork-io/terratest#323]
Hey!

I'm new to terratest, so in case this question is completely out of scope, my apologies in advance.

Basically, I'm trying to test a terraform module that deploys a fluentd instance, and I just want to check the port is reachable from where I'm running terratest, this would be within a context of a CI/CD pipeline, just to ensure the module is at least up and running and reachable.

Is this something terratest or go could do? Or not a recommended practice?

For the provisioning part I'm using an ansible role that is already tested by molecule on separate project, so I'm avoiding SSHing into the instance and repeat those tests again.

Maybe this is not the right use case for terratest, and to make this type of test more meaningful I should probably test this module with the entire EFK stack, to actually ensure the logs are reaching the ES cluster.

Would appreciate some guidelines here and references for best practices.

**Comment by yorinasub17** [comment]
Hi @carlos4ndre welcome to terratesting!

Checking a port from the running test machine is a reasonable use of terratest. We currently only have functions for HTTP access though.

That said, there are a few ways you can accomplish your goal. The basic idea is to write a validation function that determines success, and then wrap it in a retry logic to ensure you account for provisioning delays. You can use the [HttpGetWithRetryWithCustomValidation](https://github.com/gruntwork-io/terratest/blob/master/modules/http-helper/http_helper.go#L108) as a reference.

Here are a few options you can try:

- If you had a script already that you can use to test access, you can wrap that in terratest with the `shell` module. Sometimes this is easier than using golang directly because the particular application may not have mature go client libraries.
- Since this is a concrete service (`fluentd`), you can try using [the official logger library for golang](https://github.com/fluent/fluent-logger-golang) as a validation function. I am not super familiar with it, but the docs suggest a call to `New` would be a sufficient test for accessibility, since it returns an error.
- If you are not concerned with testing the application logic, you can try using [net.Dial](https://golang.org/pkg/net/#Dial), which simply opens a TCP connection to the endpoint.
