### ISSUE TITLE
(Question) Terraform Module outside of tests

### ISSUE THREAD

**Issue by tiny-dancer** [gruntwork-io/terratest#327]
Hey, we're looking to execute terraform from golang in our application (not necessarily as testcases) and would love to re-use the terraform wrapper already in here however it has a tight coupling with `testing.T`.  

Perceived Options:
1) Contribute to `terratest` decoupling `terraform` from `testing`
2) Execute `go test` from production code

Any recommendations or preferred direction here?

NOTE: Do not believe mocking `testing.T` is option due to `*testContext`

```golang
type T struct {
	common
	isParallel bool
	context    *testContext // <-- private
}
```

Thanks!

**Comment by yorinasub17** [comment]
Hi @tiny-dancer 

I am nervous about starting to support using the modules in here for anything other than test use cases, primarily because these functions are optimized for test use cases and we want to keep it that way. For example, the command functions implement streaming `stdout` and `stderr` to the test logger so that we can parse it out later using the `terratest_log_parser`. In a production version, we would have to remove this and then introduce a layer of abstraction to support the testing use case. This may seem nice in that it supports a wider use case, but it complicates the library because you would have to be concerned about supporting the production use case, or the test use case adding decision overhead to feature development.

I would instead suggest creating a new project/library that uses the terratest patterns that is optimized for production use cases. We already do some of this at Gruntwork: for example, the `gruntwork-cli` library has a version of the `shell` module that is more optimized for production use cases (https://github.com/gruntwork-io/gruntwork-cli/tree/master/shell).

**Comment by tiny-dancer** [comment]
> I would instead suggest creating a new project/library that uses the terratest patterns that is optimized for production use cases. 

thanks @yorinasub17, we will embark on this direction.
