### ISSUE TITLE
Adding support for EKS 

### ISSUE THREAD

**Issue by rajholla** [gruntwork-io/terratest#348]
Hello ,
I am planning on adding support for [EKS](https://aws.amazon.com/eks/)
An example creating EKS control plane using Terraform and use Terratest to validate the Terraform output for the below:

**arn** - The Amazon Resource Name (ARN) of the cluster.
**certificate_authority** - Nested attribute containing certificate-authority-data for your cluster.
**enabled_cluster_log_types** - The enabled control plane logs.
**endpoint** - The endpoint for your Kubernetes API server.
**platform_version** - The platform version for the cluster.
**role_arn** - The Amazon Resource Name (ARN) of the IAM role that provides permissions for the Kubernetes control plane to make calls to AWS API operations on your behalf.
**version** - The Kubernetes server version for the cluster.
**vpc_config** - Nested attribute containing VPC configuration for the cluster.

Let me know if I can provide any additional information before I start.

**Comment by yorinasub17** [comment]
Can you describe some of the functions you are planning on exposing to help with your test validations?

**Comment by rajholla** [comment]
Hello @yorinasub17 ,
Just to verify all the rights nobs are set by getting the below: 
```
func GetEksVpcConfigE(t *testing.T, clusterName string, awsRegion string) (map[string]string,error)
func GetEksPlatformConfigE(t *testing.T, clusterName string, awsRegion string)(map[string]string,error)
func GetEksVpcConfig(t *testing.T, clusterName string, awsRegion string) map[string]string
func GetEksPlatformConfig(t *testing.T, clusterName string, awsRegion string)map[string]string
```
+ other supporting functions

**Comment by yorinasub17** [comment]
Hmm that seems like it would be verbose, and would lead to function sprawl. After all, we don't want to have wrappers for every single function that is already available in the aws go SDK since that is a moving target and would be hard to maintain.

Can you think of a few key functions to wrap in the aws go SDK that returns enough information, and then return an EKS struct that has all the info you need?

Also, another thing to think about is what makes it hard about the AWS go SDK that makes it hard to verify these things. How many function calls to make? Is the struct so nested that it is confusing? Etc.

In some cases, the go SDK is not so bad that you can use it directly; in others, it is so difficult that you will always get lost and always have bugs (E.g forgetting to call a second function). The latter case is when it makes sense to have terratest verification function.

**Comment by rajholla** [comment]
@yorinasub17  thank you for the pointers. I am going to spend some time tomorrow to figure out the best way to handle this.

**Comment by rajholla** [comment]
I learnt bit more about the idea of helper functions. It made lot more sense to use AWS go sdk directly  for my specific use case. Thank you for the inputs.

**Comment by yorinasub17** [comment]
@bj-1795 As indicated in the last comment, we opted for using the AWS SDK go functions directly instead of adding functions in terratest. If you have specific functionality you need, can you open a new ticket describing what functions you are looking for? This should answer the questions mentioned in https://github.com/gruntwork-io/terratest/issues/348#issuecomment-519325078
