### ISSUE TITLE
[Feature]: Allow ability to specify Namespace in NewKubectlOptions

### ISSUE THREAD

**Issue by BrendanThompson** [gruntwork-io/terratest#354]
If you look at the `struct` definition for `KubectlOptions` it has attributes for the `Namespace`, this is not implemented by the `NewKubectlOptions()` func ( _As can be seen below_ ). Is the premise here to make it the responsibility of the caller to create an instance of the struct without using the aforementioned func when they require explicit declaration of the `Namespace` attribute?

https://github.com/gruntwork-io/terratest/blob/f8167b3905e7b41b2cd5f20a8bd7b2696e7f93dd/modules/k8s/kubectl_options.go#L13

An option would be to extend the current implementation of the `NewKubectlOptions()` func to be something like:
```go
func NewKubectlOptions(contextName string, configPath string, namespace string, env map[string]string) *KubectlOptions {
	return &KubectlOptions{
		ContextName: contextName,
		ConfigPath:  configPath,
		Namespace: namespace,
		Env: env,
	}
}
```
This includes both `Namespace` and `Env`, the only issue here is the fact that the caller would then always need to include these values. My `go` knowledge isn't that great. The other alternative would be to remove `Env` and only allow `Namespace`, further as `Namespace` is a string it could also be defaulted in the struct.

**Comment by yorinasub17** [comment]
This was to be backwards compatible with previous releases so that you didn't have to update all instances of `NewKubectlOptions`, which would be quite a lot. Originally many tests we were writing were done against the default Namespace so it was rare for us to specify a specific Namespace.

However, over time as we wrote more tests, it became clear that it would be nice to have the Namespace unique per test so nowadays almost all our tests have an immediate line to update the Namespace. For example:

```
options := NewKubectlOptions("", "")
options.Namespace = uniqueNamespace()
```

Given this pattern is now recommended, it probably makes sense to update `NewKubectlOptions` to accept the namespace as a param.

If you are curious about the design: in general, we don't want to take in all the params of the struct for the constructor because then it wouldn't be any different than manually constructing it using the struct call with `{}`. We usually only include the options that are almost always set, while excluding those that are only set occasionally and have them set to a sane default in the constructor function.

**Comment by BrendanThompson** [comment]
@yorinasub17 that makes sense! Definitely agree though the standard with Kubernetes now is certainly around using `namespaces`.

In terms of your design, that absolutely makes sense! To be honest I didn't even think about just setting the attribute like you've demonstrated above.

**Comment by j4ng5y** [comment]
I'll make this happen 😄

**Comment by yorinasub17** [comment]
This is done in https://github.com/gruntwork-io/terratest/releases/tag/v0.20.0
