### ISSUE TITLE
Does the cost in AWS increase? 

### ISSUE THREAD

**Issue by ismferd** [gruntwork-io/terratest#401]
Hi,

I stated today playing with Terratest and I have some questions (I was looking for the answer but I didn't get). 
- When I call to run test, Terratest will create my stack in AWS (in my case), right? 
- If I launch the test in each commit we will increase the cost on AWS, don't I?
- What kind of test is? I mean, I look for unit test about my infra instead of e2e test.
- Why don't mock?
- If my stack is built it 3 days ago, Terratest will destroy it with `defer terraform.Destroy(t, terraformOptions)`, right? 

thanks and best

**Comment by yorinasub17** [comment]
Hi @ismferd ,

As you might have guessed, Terratest is designed more for end to end testing and less for unit testing. We and the community have explored possibilities of doing this ([plan testing](https://github.com/gruntwork-io/terratest/issues/280), using [moto server](https://github.com/spulec/moto), [terraform unit testing](https://github.com/hashicorp/terraform/issues/21628)). All of these solutions have different challenges that make them not a full solution.

In general, if you are doing something very simple (e.g launching a single RDS instance or a few EC2 instances or a VPC) you might be able to write a test using any of the above ideas, but for anything more complicated (e.g a module to deploy kafka), a test using mocking is probably not going to give you the full picture or confidence that your module works.

You can read more about the terratest philosophy here: https://github.com/gruntwork-io/terratest#testing-best-practices

As for the other questions:

> When I call to run test, Terratest will create my stack in AWS (in my case), right?

Yes

> If I launch the test in each commit we will increase the cost on AWS, don't I?

Yes

> If my stack is built it 3 days ago, Terratest will destroy it with `defer terraform.Destroy(t, terraformOptions)`, right?

Not quite. `defer` essentially delays the function call until the end of the test, even if there is an error. However, if the test process is killed (E.g due to timeout from the CI server) before it had a chance to run the deferred call, then the infrastructure will stay up and you will have to manually destroy it.

To handle this, you can use [cloud-nuke](https://github.com/gruntwork-io/cloud-nuke/) to periodically clean up remaining infrastructure in your account.


---

Hope this helps!

**Comment by ismferd** [comment]
Thanks a lot @yorinasub17 
The answer is so useful to me
