### ISSUE TITLE
helm/testing: no release name definition in template rendering

### ISSUE THREAD

**Issue by StupidScience** [gruntwork-io/terratest#402]
There is no possibility to define release name when you render a template.

**Comment by yorinasub17** [comment]
This would be a good thing to add! We are a bit buried at the moment, but a PR to implement this would be very welcome!

In terms of implementation, currently release name is a positional arg in `Install` and `Delete`, but it is probably better in the options (https://github.com/gruntwork-io/terratest/blob/master/modules/helm/options.go#L7), since all the commands can make use of it.
