### ISSUE TITLE
Should the set of examples work with terraform v0.12.12

### ISSUE THREAD

**Issue by ggrover** [gruntwork-io/terratest#418]
I noticed that running the test against `examples/terraform-aws-example` failed as it was missing ` tags = {` after the
Just wondering if the tests should be working against terraform v0.12.12?

**Comment by brikis98** [comment]
@ggrover Hm, you're right, the examples haven't been updated for 0.12.x, even though the library itself has!

@yorinasub17 It looks like we're still using Terraform 0.11 in the CI env for Terratest?

**Comment by yorinasub17** [comment]
> It looks like we're still using Terraform 0.11 in the CI env for Terratest?

Yes. This was because this place is the only place currently that validates Terratest works with tf11, since all our other repos validates tf12 support.

With that said, at this point, I would like to propose we drop support for tf11. This will involve:

- Updating examples to use tf12
- Drop forking of output functions based on tf version
- Update CI environment to tf12

**Comment by brikis98** [comment]
@yorinasub17 Ah, gotcha. +1 on what you suggested.

**Comment by brikis98** [comment]
Note that it's not super high priority, as we know Terratest works with TF12. Perhaps punt until after CIS work?

**Comment by yorinasub17** [comment]
This is now resolved. Beginning with [v0.24.0](https://github.com/gruntwork-io/terratest/releases/tag/v0.24.0), all examples have been updated to tf12 and tf11 support was dropped.
