### ISSUE TITLE
Can terratest be used to run tests against an existing k8s infrastructure(production environment)?

### ISSUE THREAD

**Issue by charudut** [gruntwork-io/terratest#443]
I came across terratest through a colleague of mine, looks like its a pretty solid testing framework. But from what I have gathered the way terratest works is, it will do the deployment by creating AWS resources(EC2, S3, ELB etc.) and then bring up the microservices on these resources(Kubernetes/Helm), run tests and destroy all microservices and AWS resources in the end, is my understanding correct here?

Could terratest be used to test already deployed infrastructure? my team has already setup a k8s cluster, which means the AWS resources are already provisioned. At this point I want to run terratest to check if

a. all the required microservices are up and running(maybe each microservice has a health check endpoint I can hit to get a 200?)
b. some of the microservices, which have a dependency i.e. requires db access, requires an S3 bucket, have their dependencies met
b. all the AWS resources being created, they are healthy, and their configurations(CPU, memory, disk size etc.) is what we expect

And at the end of the test run, I don't want terratest to destroy any components of my k8s cluster. this will be extremely useful when my team makes small updates to the infrastructure and pushes changes, so I can use terratest to do sanity check and verify the infrastructure state is healthy.

Can this requirement be met by terratest or should I be looking at alternate solutions for my use case? if so, can you give me some pointers on what I should be looking at? thank you.

**Comment by yorinasub17** [comment]
Terratest does support this use case, although it is not the primary use case of terratest. For these types of tests, you can remove the apply and delete steps from your test and focus on the validation functions.

Note that because this isn't the primary use case, we don't have a lot of examples, and we might be missing functions. For example, for (a) I would expect you would want to interact with the `Deployment`, but we don't have any functions for `Deployment` yet. For most test cases that confirms charts and infrastructure, we operate on a small scale such that it isn't necessary to check the `Deployment` and it is much better to go through the `Service`.

I would suggest starting by going through some of the examples that interact with the objects, and see which functions you can reuse for your validation tests. [This test](https://github.com/gruntwork-io/terratest/blob/master/test/kubernetes_basic_example_service_check_test.go#L54) is probably a good starting point, where we check the service endpoint to see if we get a healthy response.

**Comment by charudut** [comment]
Hello @yorinasub17 , thank you for replying to my question. when you refer to `Deployment` you mean the actual micro service app, for example a login web app running on k8s, correct? so, to validate terraform and charts minus the service, I can use terratest, correct? thanks for the linked example test, I'll take a look at it.

**Comment by yorinasub17** [comment]
By `Deployment` I am referring to the [Kubernetes Deployment resource](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/). If you look at [the functions in the `k8s` module](https://godoc.org/github.com/gruntwork-io/terratest/modules/k8s), you will notice that a lot of them are wrappers around the Kubernetes client-go library for getting the specific Kubernetes resources into the go struct maintained by the client-go library. So if you wanted to validate things like "is the health check passing?", you would want to grab the corresponding resource (in this case `Deployment`) and validate the status on the resource.

**Comment by charudut** [comment]
great, thanks for clarifying, @yorinasub17. cheers!

**Comment by yorinasub17** [comment]
Going to close this out, but feel free to open new issues if you run into more specific questions during your implementation.
