### ISSUE TITLE
AWS session token - terraform.tfstate not pushed to S3

### ISSUE THREAD

**Issue by pyguy** [gruntwork-io/terratest#444]
Hi,
seems to be an inconsistent behavior on terraform when using AWS session tokens. the issue is that the EKS cluster creation part is too slow that times out most of the time making my tests frustrating and time consuming!

related issue: https://github.com/terraform-providers/terraform-provider-aws/issues/3126

**Comment by yorinasub17** [comment]
Since this is a terraform issue, there isn't much that terratest can do. Note that we usually don't recommend using remote state for terratest primarily for issues like you are encountering here. The general strategy is to use local state (so that you always have the state between the apply and destroy), and to use a test account that can be periodically nuked for test failures (using a tool such as [cloud-nuke](https://github.com/gruntwork-io/cloud-nuke/)).

With that said, since terratest is using a general purpose programming language, you could embed the logic to handle the s3 state in the test code itself as a special test stage. The logic would be:

- Find `errored.tfstate` in the working directory
- Store it somewhere that is secure (since it contains secrets) and is not AWS (since the failure to push `errored.tfstate` indicates an access failure)
- (If CI) run a special stage that will run `terraform state push` on the `errored.tfstate` file with refreshed access credentials if the previous stage failed.
