### ISSUE TITLE
Godocs don't display on pkg.go.dev due to license policy

### ISSUE THREAD

**Issue by jlucktay** [gruntwork-io/terratest#533]
On the newer [pkg.go.dev](https://pkg.go.dev) site, the [godocs for terratest](https://pkg.go.dev/github.com/gruntwork-io/terratest?tab=doc) aren't displaying due to some licensing restrictions:
![image](https://user-images.githubusercontent.com/460028/83028598-8db87200-a029-11ea-88f8-98ae822025ab.png)

The [license policy there](https://pkg.go.dev/license-policy) states that they do detect and recognise Apache-2.0 which seems to line up with the [license file in the repo](https://github.com/gruntwork-io/terratest/blob/master/LICENSE) so it looks like some crossed wires somewhere.
Their license policy page also has a few different avenues to remedy.

**Comment by yorinasub17** [comment]
I think the real issue is that it is detecting `v0.7.14` as the latest version, when that is actually a really old version of terratest. If you go directly to a newer version, it renders correctly (See https://pkg.go.dev/github.com/gruntwork-io/terratest@v0.27.5 for example).

Need more investigation to see why that version is marked as latest though.

**Comment by yorinasub17** [comment]
Ok figured out the issue. This is pointing to the first version of terratest that was not using dep, and thus is not gomodules compatible. The correct URL is https://pkg.go.dev/mod/github.com/gruntwork-io/terratest . This is the URL that you get if you search terratest in the search bar at `pkg.go.dev`.
