### ISSUE TITLE
TestImportSSHKeyOSLogin failing

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terratest#536]
[CircleCi Build](https://circleci.com/gh/gruntwork-io/terratest/3286)
[Build log](https://3286-53174289-gh.circle-artifacts.com/0/tmp/logs/TestImportSSHKeyOSLogin.log)

```
=== RUN   TestImportSSHKeyOSLogin
=== PAUSE TestImportSSHKeyOSLogin
=== CONT  TestImportSSHKeyOSLogin
TestImportSSHKeyOSLogin 2020-05-29T14:21:09Z key_pair.go:31: Generating new public/private key of size 2048
TestImportSSHKeyOSLogin 2020-05-29T14:21:10Z oslogin.go:27: Importing SSH key for user circleci@terratest-214610.iam.gserviceaccount.com
TestImportSSHKeyOSLogin 2020-05-29T14:21:10Z oslogin.go:61: Deleting SSH key for user circleci@terratest-214610.iam.gserviceaccount.com
TestImportSSHKeyOSLogin 2020-05-29T14:21:10Z oslogin.go:101: Getting login profile for user circleci@terratest-214610.iam.gserviceaccount.com
--- FAIL: TestImportSSHKeyOSLogin (1.01s)
    oslogin.go:20: 
        	Error Trace:	oslogin.go:20
        	            				oslogin_test.go:18
        	Error:      	Received unexpected error:
        	            	googleapi: Error 400: Login profile size exceeds 32 KiB. Delete profile values to make additional space., badRequest
        	Test:       	TestImportSSHKeyOSLogin
        	Messages:   	Could not add SSH Key to user circleci@terratest-214610.iam.gserviceaccount.com
```

**Comment by brikis98** [comment]
@robmorgan Do we need to clean something up in one of our GCP accounts?

**Comment by robmorgan** [comment]
@brikis98 yes we do, it looks like our test IAM user has too many public keys associated with this. I'll look into this, this week.

**Comment by brikis98** [comment]
Roger, thx Rob!

**Comment by robmorgan** [comment]
Yori and I looked at the imported SSH keys for the Terratest CircleCI user and found they were at the 70 limit. See https://github.com/gruntwork-io/terratest/pull/298 for more context.

We've cleaned the keys now, but what may be occurring is an intermittent cleanup failure where the keys are not removed during a build. If that's the case we need to identify where that is and fix the root cause. Alternatively, if builds are canceled before the cleanup properly occurs, then this issue will likely happen again in the future, therefore follow the steps below to clean up the SSH keys.

### Cleaning up the OSLogin SSH Keys

1. Run a build with SSH access for the `test` build.
1. Ensure `GOOGLE_APPLICATION_CREDENTIALS` is set.
1. Activate the service account for `gcloud` by running `gcloud auth activate-service-account $GOOGLE_IDENTITY_EMAIL --key-file=$GOOGLE_APPLICATION_CREDENTIALS`.
1. List the SSH Keys: `gcloud compute os-login ssh-keys list`
1. Write the key fingerprints to a file: `gcloud compute os-login ssh-keys list | tail -n+2 > keys.txt`
1. Delete each key sequentially: `cat keys.txt | xargs -L1 -I {} -t gcloud compute os-login ssh-keys remove --key={} ;`

**Comment by brikis98** [comment]
Thanks Rob and Yori for getting this resolved!
