### ISSUE TITLE
Update Namespace with metadata

### ISSUE THREAD

**Issue by austince** [gruntwork-io/terratest#575]
Hey all, I'm using the `k8s.CreateNamespace` functions to create namespaces but need to add labels/ other metadata to the objects. It doesn't look like there is currently a way to do this, but please correct me if I'm wrong!

See:
https://github.com/gruntwork-io/terratest/blob/29b36ae7b3ff22f19ec844ab4b6d0699574af92d/modules/k8s/namespace.go#L14-L32

Would a PR be accepted that either:
a) allows passing in a `corev1.Namespace` to create
b) creates new methods for updating a namespace after creation

Thanks!

**Comment by yorinasub17** [comment]
Can you elaborate on what the use case is for the metadata? Is it to distinguish test namespaces from others in your cluster?

I am a bit hesitant to add this in since it complicates the API for what seems like an uncommon use case (note [our contribution guideline](https://terratest.gruntwork.io/docs/community/contributing/#infrastructure-and-validation-helpers), and specifically about "creating infrastructure"), but I may be wrong.

In any case, replacing the `namespaceName` arg with a `namespaceOpts` struct would keep the API relatively simple while allowing setting those options, so perhaps that is the way to go.

**Comment by austince** [comment]
Hey @yorinasub17, sorry for the late reply. That totally makes sense to me and thanks for the thorough explanation. One use case would be for adding labels needed by service meshes to enable sidecar injection. 
Examples:
* kuma: https://kuma.io/docs/0.6.0/documentation/overview/#kubernetes-mode
* istio: https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/

Do you think that is too specific? A workaround would be to create the namespace with terratest and then wait to update it through the k8s client directly.

**Comment by yorinasub17** [comment]
Ah gotcha. That makes sense actually. In that case, happy to review a PR that updates this! 👍 

Perhaps for backwards compatibility, we can create a new function `CreateNamespaceWithMetadata` that takes in the `namespaceOpts` struct, and keep the existing function signature for `CreateNamespace` but under the hood it calls `CreateNamespaceWithMetadata`?

**Comment by austince** [comment]
Sounds good to me! I won't have time to get to this for a week or two, so if anyone else stumbles upon this/ has time, no protectiveness over implementing this feature from me :)
