### ISSUE TITLE
Terratest with Terraform: Inappropriate value for attribute "ssh_keys": list of string required.

### ISSUE THREAD

**Issue by andycockers** [gruntwork-io/terratest#747]
Hi,

I'm trying to use Terratest to run my Terraform hetzner cloud code. However, I'm blocked by an issue.

When Terratest tries to apply, it fails with:

```
[0m  on main.tf line 10, in resource "hcloud_server" "node1":
        	            	  10:   ssh_keys    = [4mvar.ssh_keys[0m
        	            	[0m    [90m|----------------[0m
        	            	[0m    [90m|[0m [1mvar.ssh_keys[0m is "[\"my-ssh-key\"]"[0m
        	            	[0m
        	            	Inappropriate value for attribute "ssh_keys": list of string required.
```

My Terratest code looks like:

```
ssh_keys := []string{"my-ssh-key"}

Vars: map[string]interface{}{
			"server_name":  ServerName,
			"image_name":   "xx",
			"server_type":  "cx11",
			"location":     "fsn1",
			"ssh_keys":     ssh_keys,
			"hcloud_token": hcloudToken,
			"name":         ServerName,
		},
```
As far as I can tell, this should work, but does not.

**Comment by yorinasub17** [comment]
Do you have `type = list(string)` set explicitly on the `variable` block in your terraform module? Since these are passed in json encoded via the `-var` CLI, you need to provide type assistance to terraform for it to properly decode the variables from the CLI args.

Alternatively, you can use `VarFiles` to pass through the vars, which will do implicit type matching (since terraform can parse the var file). This would be a workaround if you don't have control over the module.

**Comment by andycockers** [comment]
Thank you, that fixed the issue for me.
