### ISSUE TITLE
Make possible to use Terraform init -reconfigure

### ISSUE THREAD

**Issue by renanqts** [gruntwork-io/terratest#839]
I didn't find a way or issue here mentioning a way to pass -reconfigure into TF init.

https://github.com/gruntwork-io/terratest/blob/09df87fed520518a32aa8423a70258a312e475fc/modules/terraform/options.go#L40-L71

Terraform reconfigure makes easy to fix issues in the backend

https://www.terraform.io/docs/cli/commands/init.html#backend-initialization

**Comment by yorinasub17** [comment]
Seems reasonable to add a new option for to configure it! We are a bit buried with other initiatives, so most likely won't get to implement this anytime soon, but happy to review a PR if you are up for it.

**Comment by wasfree** [comment]
Since terraform v0.15.4 behavior on terraform init has changed. If init now encounters a change to the stored backend configuration, it will always return an error when neither -reconfigure or -migrate-state is supplied. This change was merged in https://github.com/hashicorp/terraform/pull/28718 . PR to add this missing options has been raised see: https://github.com/gruntwork-io/terratest/pull/923
