### ISSUE TITLE
cannot use &rg (type *"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-10-01/resources".Group

### ISSUE THREAD

**Issue by tmitra1990** [gruntwork-io/terratest#934]
I am getting this error 
+ go test -v -tags azure
# github.com/gruntwork-io/terratest/modules/azure
../../jobs/test-go/builds/252/pkg/mod/github.com/gruntwork-io/terratest@v0.35.6/modules/azure/resourcegroup.go:78:9: cannot use &rg (type *"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-10-01/resources".Group) as type *"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-06-01/resources".Group in return argument
../../jobs/test-go/builds/252/pkg/mod/github.com/gruntwork-io/terratest@v0.35.6/modules/azure/resourcegroup.go:100:18: cannot use rg.Values() (type []"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-10-01/resources".Group) as type []"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-06-01/resources".Group in return argument
FAIL	github.com/tmitra1990/IAC_POC [build failed]

Please help me to resolve this issue. Previously same code was working fine after recent changes i am facing this issue. Go version 1.16.4

_Originally posted by @tmitra1990 in https://github.com/gruntwork-io/terratest/issues/894#issuecomment-863178503_

**Comment by yorinasub17** [comment]
Hi how are you including/fetching terratest in your project? (Specifically, what `go get` call did you make, if any?)

**Comment by yorinasub17** [comment]
Can you also try running `go mod tidy` to see if that resolves the dependency issues for you?

**Comment by tmitra1990** [comment]
I used 'go get github.com/gruntwork-io/terratest/modules/azure' and i tried to use 'go get -v -u github.com/gruntwork-io/terratest' as well and got this error "../../jobs/test-go/builds/251/pkg/mod/github.com/!azure/azure-sdk-for-go@v55.2.0+incompatible/services/keyvault/auth/auth.go:11:2: missing go.sum entry for module providing package github.com/Azure/go-autorest/autorest/azure/auth (imported by github.com/gruntwork-io/terratest/modules/azure); to add:
	go get github.com/gruntwork-io/terratest/modules/azure@v0.35.6". 
Let me know where to use go mod tidy in my jenkins file after go get? I tried using it after go get not working.

**Comment by tmitra1990** [comment]
Just for your information this code was working absolutely fine last week. I believe becoz of the new changes introduced in the azure module i am facing this issue.

**Comment by yorinasub17** [comment]
> Just for your information this code was working absolutely fine last week. I believe becoz of the new changes introduced in the azure module i am facing this issue.

**Comment by yorinasub17** [comment]
> Just for your information this code was working absolutely fine last week. I believe becoz of the new changes introduced in the azure module i am facing this issue.

The reason it's no longer working is because your project is using a different version of the azure SDK for go than what terratest is using/testing.

In your logs, you can see that you have `v55.2.0` installed, but terratest requires `v46.0.0`.

The problem is that you are using `go get` to fetch the dependency, which has different rules for respecting transitive dependencies than the `go.mod` file. To ensure stable dependency fetching, it's recommended to setup a go modules file and avoid `go get`; `go get` should only be used in the initial phase of setting up your `go.mod` file.

Try the following steps:

1a. If you have a `go.mod` file in your project already, sanitize it to make sure it's not directly pulling in azure SDK for go.
1b. If you don't have a `go.mod` file, run `go mod init` to set it up.
2. Once the `go.mod` file is setup, remove (if any) the `go.sum` file.
3. Run `go mod tidy` to ensure the dependencies versions are locked.
4. Check in the `go.mod` and `go.sum` files. Now you won't need to run any `go get` calls to pull in the dependencies in your environment.
5. Update your CI script to remove the `go get` calls because they are no longer necessary - `go test` will automatically pull down the necessary dependencies, at the right versions, using the `go.mod` and `go.sum` files as references.

**Comment by yorinasub17** [comment]
Woops accidentally closed

**Comment by tmitra1990** [comment]
One doubt how to downgrade from v55.2.0 to v46.0.0? I have removed all the go get command. i used only go mod init. Now i am getting this error "../../jobs/test-go/builds/256/pkg/mod/github.com/!azure/azure-sdk-for-go@v55.2.0+incompatible/services/compute/mgmt/2020-06-01/compute/models.go:950:2: undefined: azure.FutureAPI" while importing.

**Comment by yorinasub17** [comment]
After `go mod init`, did you run `go mod tidy`? If so, is there any direct reference to azure sdk for go in your test files? That might be what is causing your project to pull up the go dependency to latest.

**Comment by tmitra1990** [comment]
Yes i ran go mod tidy after go mod init and in my test file i am importing github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-06-01/compute which is throwing error currently.

**Comment by yorinasub17** [comment]
Can you add (or replace if it already exists) the directive for azure-sdk-for-go in your `go.mod` file to:

```
github.com/Azure/azure-sdk-for-go v46.0.0+incompatible
```

and run `go mod tidy` again?

**Comment by tmitra1990** [comment]
@yorinasub17 Thanks for your help i am able to run my code.

**Comment by tmitra1990** [comment]
I am closing this issue.
